### ISSUE TITLE
Make it look better without using any thirdparty framework

### ISSUE THREAD

**Issue by yilkalargaw** [yilkalargaw/direct_download_stalker#3]

**Comment by neeraj15022001** [comment]
i can work on this one

**Comment by yilkalargaw** [comment]
Awesome give it a go and send a pull request.

**Comment by neeraj15022001** [comment]
shall i create a design first or should i directly implement it ?

**Comment by neeraj15022001** [comment]
![LOADING SCREEN](https://user-images.githubusercontent.com/55191873/135533502-7b58dff2-dfdf-4c35-9043-7eea77abd823.png)
Loading Screen
![MacBook Pro - 2](https://user-images.githubusercontent.com/55191873/135533510-54e65304-4ec1-4a3a-8b15-02c7cfdb2d31.png)


and a background like this could be added
![Screenshot 2021-10-01 at 3 07 21 AM](https://user-images.githubusercontent.com/55191873/135533581-52cb039f-4367-40c8-9ea4-5c71613df183.png)

**Comment by yilkalargaw** [comment]
I like the design. The patterned background may not be necessary. Even if it is not a good practice try and keep all the styling in the html file so that one could simply download and use it easily.

**Comment by neeraj15022001** [comment]
if we use tailwind css then it can save mess up in HTML file, if i will write custom CSS that will create mess in HTML file ?

**Comment by yilkalargaw** [comment]
Maybe something that could easily be loaded from a CDN.

**Comment by neeraj15022001** [comment]
https://tailwindcss.com/docs/installation#using-tailwind-via-cdn. Checkout here it is available via CDN

**Comment by neeraj15022001** [comment]
Note that while the CDN build is large (72.8kB compressed, 2936.0kB raw), it's not representative of the sizes you see when including Tailwind as part of your build process

**Comment by yilkalargaw** [comment]
I am worried about people being able to download it and simply opening it in their browser incase they need to use it locally. Some people use the file that way.

**Comment by neeraj15022001** [comment]
So then should i write custom CSS then ?

**Comment by neeraj15022001** [comment]
i am flexible with both

**Comment by yilkalargaw** [comment]
I think that might be better. If it is too much work I'm okay with you picking a simpler design.

**Comment by neeraj15022001** [comment]
I will work this design out not a problem

**Comment by yilkalargaw** [comment]
Awesome :+1:

**Comment by yilkalargaw** [comment]
Thank you very much @neeraj15022001.
